export const langs = [
  {
    name: "JavaScript",
    type: "programming",
    extensions: [
      ".js",
      "._js",
      ".bones",
      ".es",
      ".es6",
      ".frag",
      ".gs",
      ".jake",
      ".jsb",
      ".jscad",
      ".jsfl",
      ".jsm",
      ".jss",
      ".njs",
      ".pac",
      ".sjs",
      ".ssjs",
      ".sublime-build",
      ".sublime-commands",
      ".sublime-completions",
      ".sublime-keymap",
      ".sublime-macro",
      ".sublime-menu",
      ".sublime-mousemap",
      ".sublime-project",
      ".sublime-settings",
      ".sublime-theme",
      ".sublime-workspace",
      ".sublime_metrics",
      ".sublime_session",
      ".xsjs",
      ".xsjslib",
    ],
  },
  {
    name: "Apex",
    type: "programming",
    extensions: [".cls"],
  },
  {
    name: "Batchfile",
    type: "programming",
    extensions: [".bat", ".cmd"],
  },
  {
    name: "C",
    type: "programming",
    extensions: [".c", ".cats", ".h", ".idc", ".w"],
  },
  {
    name: "C#",
    type: "programming",
    extensions: [".cs", ".cake", ".cshtml", ".csx"],
  },
  {
    name: "C++",
    type: "programming",
    extensions: [
      ".cpp",
      ".c++",
      ".cc",
      ".cp",
      ".cxx",
      ".h",
      ".h++",
      ".hh",
      ".hpp",
      ".hxx",
      ".inc",
      ".inl",
      ".ipp",
      ".tcc",
      ".tpp",
    ],
  },
  {
    name: "Clojure",
    type: "programming",
    extensions: [
      ".clj",
      ".boot",
      ".cl2",
      ".cljc",
      ".cljs",
      ".cljs.hl",
      ".cljscm",
      ".cljx",
      ".hic",
    ],
  },
  {
    name: "CoffeeScript",
    type: "programming",
    extensions: [".coffee", "._coffee", ".cake", ".cjsx", ".cson", ".iced"],
  },
  {
    name: "CSS",
    type: "markup",
    extensions: [".css"],
  },
  {
    name: "CSV",
    type: "data",
    extensions: [".csv"],
  },
  {
    name: "XML",
    type: "data",
    extensions: [
      ".xml",
      ".ant",
      ".axml",
      ".ccxml",
      ".clixml",
      ".cproject",
      ".csl",
      ".csproj",
      ".ct",
      ".dita",
      ".ditamap",
      ".ditaval",
      ".dll.config",
      ".dotsettings",
      ".filters",
      ".fsproj",
      ".fxml",
      ".glade",
      ".gml",
      ".grxml",
      ".iml",
      ".ivy",
      ".jelly",
      ".jsproj",
      ".kml",
      ".launch",
      ".mdpolicy",
      ".mm",
      ".mod",
      ".mxml",
      ".nproj",
      ".nuspec",
      ".odd",
      ".osm",
      ".plist",
      ".pluginspec",
      ".props",
      ".ps1xml",
      ".psc1",
      ".pt",
      ".rdf",
      ".rss",
      ".scxml",
      ".srdf",
      ".storyboard",
      ".stTheme",
      ".sublime-snippet",
      ".targets",
      ".tmCommand",
      ".tml",
      ".tmLanguage",
      ".tmPreferences",
      ".tmSnippet",
      ".tmTheme",
      ".ts",
      ".tsx",
      ".ui",
      ".urdf",
      ".ux",
      ".vbproj",
      ".vcxproj",
      ".vssettings",
      ".vxml",
      ".wsdl",
      ".wsf",
      ".wxi",
      ".wxl",
      ".wxs",
      ".x3d",
      ".xacro",
      ".xaml",
      ".xib",
      ".xlf",
      ".xliff",
      ".xmi",
      ".xml.dist",
      ".xproj",
      ".xsd",
      ".xul",
      ".zcml",
    ],
  },
  {
    name: "Dart",
    type: "programming",
    extensions: [".dart"],
  },
  {
    name: "Dockerfile",
    type: "data",
    extensions: [".dockerfile"],
  },
  {
    name: "Go",
    type: "programming",
    extensions: [".go"],
  },
  {
    name: "GraphQL",
    type: "data",
    extensions: [".graphql"],
  },
  {
    name: "Handlebars",
    type: "markup",
    extensions: [".handlebars", ".hbs"],
  },
  {
    name: "HTML",
    type: "markup",
    extensions: [".html", ".htm", ".html.hl", ".inc", ".st", ".xht", ".xhtml"],
  },
  {
    name: "INI",
    type: "data",
    extensions: [".ini", ".cfg", ".prefs", ".pro", ".properties"],
  },
  {
    name: "Java",
    type: "programming",
    extensions: [".java"],
  },
  {
    name: "Java Server Pages",
    type: "programming",
    extensions: [".jsp"],
  },
  {
    name: "Less",
    type: "markup",
    extensions: [".less"],
  },
  {
    name: "Kotlin",
    type: "programming",
    extensions: [".kt", ".ktm", ".kts"],
  },
  {
    name: "JSON",
    type: "data",
    extensions: [".json", ".geojson", ".lock", ".topojson"],
  },
  {
    name: "Objective-C",
    type: "programming",
    extensions: [".m", ".h"],
  },
  {
    name: "Objective-C++",
    type: "programming",
    extensions: [".mm"],
  },
  {
    name: "Markdown",
    type: "prose",
    extensions: [".md", ".markdown", ".mkd", ".mkdn", ".mkdown", ".ron"],
  },
  {
    name: "Lua",
    type: "programming",
    extensions: [".lua", ".fcgi", ".nse", ".pd_lua", ".rbxs", ".wlua"],
  },
  {
    name: "Pascal",
    type: "programming",
    extensions: [".pas", ".dfm", ".dpr", ".inc", ".lpr", ".pp"],
  },
  {
    name: "Perl",
    type: "programming",
    extensions: [
      ".pl",
      ".al",
      ".cgi",
      ".fcgi",
      ".perl",
      ".ph",
      ".plx",
      ".pm",
      ".pod",
      ".psgi",
      ".t",
    ],
  },
  {
    name: "Perl6",
    type: "programming",
    extensions: [
      ".6pl",
      ".6pm",
      ".nqp",
      ".p6",
      ".p6l",
      ".p6m",
      ".pl",
      ".pl6",
      ".pm",
      ".pm6",
      ".t",
    ],
  },
  {
    name: "PHP",
    type: "programming",
    extensions: [
      ".php",
      ".aw",
      ".ctp",
      ".fcgi",
      ".inc",
      ".php3",
      ".php4",
      ".php5",
      ".phps",
      ".phpt",
    ],
  },
  {
    name: "PLpgSQL",
    type: "programming",
    extensions: [".sql"],
  },
  {
    name: "Text",
    type: "prose",
    extensions: [".txt", ".fr", ".nb", ".ncl", ".no"],
  },
  {
    name: "Ruby",
    type: "programming",
    extensions: [
      ".rb",
      ".builder",
      ".fcgi",
      ".gemspec",
      ".god",
      ".irbrc",
      ".jbuilder",
      ".mspec",
      ".pluginspec",
      ".podspec",
      ".rabl",
      ".rake",
      ".rbuild",
      ".rbw",
      ".rbx",
      ".ru",
      ".ruby",
      ".thor",
      ".watchr",
    ],
  },
  {
    name: "Rust",
    type: "programming",
    extensions: [".rs", ".rs.in"],
  },
  {
    name: "SAS",
    type: "programming",
    extensions: [".sas"],
  },
  {
    name: "SCSS",
    type: "markup",
    extensions: [".scss"],
  },
  {
    name: "R",
    type: "programming",
    extensions: [".r", ".rd", ".rsx"],
  },
  {
    name: "Python",
    type: "programming",
    extensions: [
      ".py",
      ".bzl",
      ".cgi",
      ".fcgi",
      ".gyp",
      ".lmi",
      ".pyde",
      ".pyp",
      ".pyt",
      ".pyw",
      ".rpy",
      ".tac",
      ".wsgi",
      ".xpy",
    ],
  },
  {
    name: "PowerShell",
    type: "programming",
    extensions: [".ps1", ".psd1", ".psm1"],
  },
  {
    name: "YAML",
    type: "data",
    extensions: [
      ".yml",
      ".reek",
      ".rviz",
      ".sublime-syntax",
      ".syntax",
      ".yaml",
      ".yaml-tmlanguage",
    ],
  },
  {
    name: "Visual Basic",
    type: "programming",
    extensions: [
      ".vb",
      ".bas",
      ".cls",
      ".frm",
      ".frx",
      ".vba",
      ".vbhtml",
      ".vbs",
    ],
  },
  {
    name: "TypeScript",
    type: "programming",
    extensions: [".ts", ".tsx"],
  },
  {
    name: "Tcl",
    type: "programming",
    extensions: [".tcl", ".adp", ".tm"],
  },
  {
    name: "Swift",
    type: "programming",
    extensions: [".swift"],
  },
  {
    name: "Smalltalk",
    type: "programming",
    extensions: [".st", ".cs"],
  },
  {
    name: "SQL",
    type: "data",
    extensions: [
      ".sql",
      ".cql",
      ".ddl",
      ".inc",
      ".prc",
      ".tab",
      ".udf",
      ".viw",
    ],
  },
  {
    name: "Shell",
    type: "programming",
    extensions: [
      ".sh",
      ".bash",
      ".bats",
      ".cgi",
      ".command",
      ".fcgi",
      ".ksh",
      ".sh.in",
      ".tmux",
      ".tool",
      ".zsh",
    ],
  },
  {
    name: "Scheme",
    type: "programming",
    extensions: [".scm", ".sld", ".sls", ".sps", ".ss"],
  },
];
